#include "SearchManager.hpp"
#include "hpx/runtime/components/component_factory_base.hpp"  // for HPX_REG...
#include "hpx/runtime/components/static_factory_data.hpp"     // for static_...

HPX_REGISTER_COMPONENT_MODULE();
